### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by azzozhsn** [cniweb/xmrig-monero#1]
Hey, I want to use this miner, can I pass pool and wallet address as parameters? how?

**Comment by cniweb** [comment]
Hi, you can use it with the official parameters, see:
https://xmrig.com/wizard

Example:
`docker run --rm -it cniweb/xmrig --url pool.hashvault.pro:443 --user 4AEGLF3WuPx5EqNbxEB9FW9uFEHNecCKmJuwvGZSo3qJ7Nr9gDQ3s3ciSs42XoFz59ifBmJHLPmd1cisepaSofuSHiJE4gR --pass z --donate-level 1 --tls --tls-fingerprint 420c7850e09b7c0bdcf748a7da9eb3647daf8515718f36d9ccfdd6b9ff834b14 --http-enabled --api-worker-id google --http-host 0.0.0.0 --http-port 8080 --http-access-token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c -t 8`

More information can be found here:
https://xmrig.com/docs/miner/command-line-options
